export const browserCoreExamples = [
  "autocrab browser status",
  "autocrab browser start",
  "autocrab browser stop",
  "autocrab browser tabs",
  "autocrab browser open https://example.com",
  "autocrab browser focus abcd1234",
  "autocrab browser close abcd1234",
  "autocrab browser screenshot",
  "autocrab browser screenshot --full-page",
  "autocrab browser screenshot --ref 12",
  "autocrab browser snapshot",
  "autocrab browser snapshot --format aria --limit 200",
  "autocrab browser snapshot --efficient",
  "autocrab browser snapshot --labels",
];

export const browserActionExamples = [
  "autocrab browser navigate https://example.com",
  "autocrab browser resize 1280 720",
  "autocrab browser click 12 --double",
  'autocrab browser type 23 "hello" --submit',
  "autocrab browser press Enter",
  "autocrab browser hover 44",
  "autocrab browser drag 10 11",
  "autocrab browser select 9 OptionA OptionB",
  "autocrab browser upload /tmp/autocrab/uploads/file.pdf",
  'autocrab browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "autocrab browser dialog --accept",
  'autocrab browser wait --text "Done"',
  "autocrab browser evaluate --fn '(el) => el.textContent' --ref 7",
  "autocrab browser console --level error",
  "autocrab browser pdf",
];
